### PR TITLE
Add support for ppc64le platform

### PR DESCRIPTION
**Pull request by kaustubh-d**
Add support for ppc64le platform. (required for RHEL7 powerpc little endian chef-client builds)

### CODE REVIEW

**Comment by kaustubh-d** [comment]
@mattray ^^

**Comment by sethvargo** [comment]
Thanks!

**Comment by kaustubh-d** [comment]
Thanks @sethvargo for merging this! Are you planning to release a newer version sooner to rubygems, it will help omnibus builds of chef-client on rhel7 powerpc little endian platform.

**Comment by sethvargo** [comment]
@kaustubh-d no release is planned at this time, sorry.

**Pull request merged**
