### PR TITLE
add init detection helpers

### PR DESCRIPTION
**Pull request by nathwill**
adds init system detection for systemd, upstart, runit

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @nathwill 

This looks good - do you think you could update the README too please?

**Comment by nathwill** [comment]
Ah, yeah, no problem. Knew I was forgetting something! :)

**Comment by nathwill** [comment]
okey doke, those README docs work OK?

**Comment by sethvargo** [comment]
Thanks!

**Comment by lamont-granquist** [comment]
@sethvargo concern that i've got is that this duplicates-ish code here:

https://github.com/chef/chef/blob/master/lib/chef/platform/service_helpers.rb

and I was intending to add create a mixin with DSL methods and include them so it was easy to use those helpers but never got around to it.  now the obvious syntax like `systemd?` will collide and could easily wind up with another `compile_time` situation.

**Comment by sethvargo** [comment]
@lamont-granquist I'm happy to remove/merge them when the APIs match. Is there an RFC for those changes you could link to?

**Comment by lamont-granquist** [comment]
Can we just get this into core chef?  At least get the tests and a mixin in core chef that we can use for provider-resolver stuff by default, then chef-sugar could just inject that mixin into the DSL recipe.

**Comment by lamont-granquist** [comment]
I think if we don't touch the Recipe DSL in core chef that we don't need to RFC it.

**Comment by sethvargo** [comment]
@lamont-granquist I don't have a problem moving this into core Chef, but I don't have the bandwidth to do that work myself. I'm not sure about @nathwill. Maybe he'd be willing to do that work.

Since this has never been released, I'm not super concerned about removing it if Chef is going to have it, but I don't want to remove it until there's a least a PR against Chef that is scheduled for triage.

**Comment by lamont-granquist** [comment]
Yeah I can't quite drop what I'm doing this second to get it fixed in core chef, but I'm very interested in seeing it ported into core chef.  If @nathwill beats me to it that would be great.  Tasks would probably be:

- tweaking the code in the service_helpers (it is still pretty much stuff i pulled out of my hat so better detection logic would be useful)
- adding a module with DSL code to Chef::DSL::ServiceDetection or something
- and the slightly tougher bit would probably be creating an object with that mixin and then changing provides blocks to be instance_eval'd against an instance of that class (or dig into what the existing context is inside provides blocks, but i suspect it'd be better to create a new object for them).
- then fix up the service providers provides? blocks to use the new sugar.

then you could just pick up the core chef DSL module and inject it into the recipe DSL and friends.

**Comment by nathwill** [comment]
@lamont-granquist happy to help get this into chef core, but not super familiar with the core codebase. i was thinking about pushing them as plugins to ohai for attributes like `node['init`]['system']`, but if you think it belongs in chef-core instead, lmk.

**Comment by lamont-granquist** [comment]
Yeah they're already in core chef.  I debated chef-vs-ohai when I wrote the provider resolver stuff for Chef 12.0.0 and went with core chef, so it should get fixed there first.  There is also rudimentary systemd detection already in ohai, and maybe it should all get unified there in the end, but offhand I cant remember exactly what I was thinking last December when I wrote it in core chef (but obviously the service detection in the core chef provider is tightly dependent on it -- i think one thing i was worried about is that if someone refactored it, they could break core chef without any spec tests in ohai necessarily failing).

If you start looking at the code in the service_helpers module and see if there's any changes you'd like to make that'd be a good start.  We probably do need to maintain the shape of those APIs, but we can fix logic in them and/or rip out the guts and just expose them as a fascade.

**Comment by sethvargo** [comment]
@lamont-granquist can we create a ticket in Chef and cross-link here for reference?

**Pull request merged**
