### PR TITLE
Add IBM s390x sugar method

### PR DESCRIPTION
**Pull request by scotthain**
@rhass @jaymalasinha @schisamo @yzl

### CODE REVIEW

**Comment by scotthain** [comment]
@sethvargo It looks like the travis failure may be transient? Would you mind giving it a retry? Thanks!

**Comment by schisamo** [comment]
:+1: I also hit retry on Travis cause apparently: http://youtu.be/_BRv9wGf5pk

**Comment by scotthain** [comment]
Thanks @schisamo - looks like chef-zero requires > 2.0.0 ruby now...

**Comment by yzl** [comment]
👍 pending travis

**Comment by sethvargo** [comment]
Travis is 😦 @scotthain

**Comment by scotthain** [comment]
@sethvargo not 100% sure how you'd like to fix travis in this case...

```Gem::InstallError: chef-zero requires Ruby version >= 2.1.0.
Installing ffi 1.9.10
An error occurred while installing chef-zero (4.6.2), and Bundler cannot
continue.
Make sure that `gem install chef-zero -v '4.6.2'` succeeds before bundling.
```

Looks like we either need to pin the chef-zero version or drop ruby 2.0.0 support. I'm happy to make whichever change you'd like to go with!

**Comment by scotthain** [comment]
Heya @sethvargo when you get a few can you let me know how you'd like to proceed with this?

**Comment by sethvargo** [comment]
We can drop 2.0

**Comment by scotthain** [comment]
@sethvargo I pinned `rack` to ~> 1.6 because the 2.x version requires Ruby 2.2.2 or greater. If you want I can remove the pin and just require Ruby 2.2.2, but this change seemed less invasive.

**Pull request merged**
